### ISSUE TITLE
The timestamp mode is not working

### ISSUE THREAD

**Issue by OValery16** [shashikg/WhisperS2T#23]
Thanks again for this very brilliant piece of work.

I realize that the mode where `without_timestamps=False` is actually not working. (Whisper doesn't detect anything)

I suspect that your prompt definition in the timestamp case is wrong (I am not 100% sure). For the reference, please find the faster_whisper [implementation](https://github.com/SYSTRAN/faster-whisper/blob/092067208b45e5eb935bfe8b0ac42b8341da9434/faster_whisper/transcribe.py#L914)

```
        if self.without_timestamps:
            prompt.append(self.tokenizer.no_timestamps)
        else:
            prompt.append(self.tokenizer.timestamp_begin)
```
Can you give me idea how to fix that ?

**Comment by shashikg** [comment]
Hi @OValery16 

Are you looking for word level timestamp? `without_timestamps` parameter is not for word level timestamp. 

To get word level timestamp use this: 
```py
model = whisper_s2t.load_model("large-v2", asr_options={'word_timestamps': True})
```

PS: Disabling `without_timestamps` will unnecessarily increase your decode time because it also predicts additional timestamp tokens like `<0.00>`, `<12.0>`, etc. Normally these timestamped tokens are predicted at utterances level and not at word levels. Use of VAD already gives you utterance level timings, so it's not really needed. 

```py
if self.without_timestamps:
    prompt.append(self.tokenizer.no_timestamps)
else:
    prompt.append(self.tokenizer.timestamp_begin)
```
BTW, this is correct and is according to OpenAI Whisper's paper. 

PS: Do you think there is any other use cases for timestamp tokens like `<0.00>`, `<12.0>`, etc ?
